server:
  port: 9000
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: swagger2word
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# Swagger json url address
# etc. https://petstore.swagger.io/
swagger.url: https://petstore.swagger.io/v2/swagger.json
